version: "3.9"
services:
  postgres-container:
    image: postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "config_file=/var/lib/postgresql/data/postgresql.conf"
    environment:
      POSTGRES_DATABASES: "$POSTGRES_DATABASE_1,$POSTGRES_USER_1:$POSTGRES_DATABASE_2,$POSTGRES_USER_2"
      POSTGRES_USERS: "$POSTGRES_USER_1,$POSTGRES_PASSWORD_1:$POSTGRES_USER_2,$POSTGRES_PASSWORD_2"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data/pgdata
      - ./database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_1} -d ${POSTGRES_DATABASE_1}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G